# Travis CI Configuration file
# @link https://travis-ci.org/

# PHP as the project language
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
env:
  # WordPress 4.3
  - WP_VERSION=4.3
  # WordPress 4.0
  - WP_VERSION=4.2
  # WordPress 4.1
  - WP_VERSION=4.1
  # WordPress 4.0
  - WP_VERSION=4.0
  # WordPress 3.9
  - WP_VERSION=3.9

before_script:
  - bash .scripts/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit